# Generated by Django 3.1.5 on 2021-03-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
